### ISSUE TITLE
Update README with little note

### ISSUE THREAD

**Issue by notbored** [Bakudankun/PICO-8.vim#2]
Think it would be helpful to mention that highlighting only works if you use a `.p8` file extension **and** have the followling lines at the top of each file:
```
pico-8 cartridge // http://www.pico-8.com
version 30
__lua__
```

It would save idiots like me a few minutes of figuring it out 😄. 

Only reason why I had the issue is because I use `#include somefile.lua`s so I can edit easily with an external editor. All you need to do to get it working is change your `.lua`s to `.p8`s and add that header to each file and then just `#include your_module.p8`.

**Comment by Bakudankun** [comment]
Sorry for late response!
Hmm I want to support that use case, because that is described in the PICO-8 manual.

First, adding next line at the top (or bottom) of the `.lua` file will instructs vim that is a pico8 file. This is Vim's modeline feature (see `:help modeline`).

```
-- vim: ft=pico8
```

However, this alone does not work for now because this plugin seeks `__lua__` line as the starting of lua code, as you said.

My opinion is that if the file does not start with `pico-8 cartridge`, treat all the file content is lua code.
Is this the right approach?

**Comment by Bakudankun** [comment]
I've implemented the above behavior. Please inform me if there is any problem. Thank you!

**Comment by notbored** [comment]
Hey sorry didn't get any notification of a response!

To me that seems like the ideal behaviour, thanks for getting to it so quickly! 

I need to start learning a bit more about Vim's internals so I can help out . I'll update the plugin and let you know if any problems arise but I doubt there will  be.
